backend:
  name: git-gateway
  branch: main
  squash_merges: true
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

media_folder: "media"
publish_mode: editorial_workflow
show_preview_links: true

collections:
  - name: "cloudDoc"
    label: "Cloud"
    folder: "cloud/stable"
    path: '{{slug}}'
    slug: '{{slug}}'
    create: true
    nested:
      depth: 100
    files:
      - name: "01_get-started"
        label: "Get Started"
        folder: "cloud/stable/01_get-started"
        path: '{{slug}}'
        slug: '{{slug}}'
        create: true
        fields:
          - {label: "Path", name: "path", widget: "string", default: "{{slug}}"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Nav Title", name: "navTitle", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "acDoc"
    label: "AC - Stable"
    folder: "ac/stable"
    path: '{{slug}}'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: "Path", name: "path", widget: "string", default: "{{slug}}"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Nav Title", name: "navTitle", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "enterpriseDoc"
    label: "Enterprise - Stable"
    folder: "enterprise/stable"
    path: '{{slug}}'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: "Path", name: "path", widget: "string", default: "{{slug}}"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Nav Title", name: "navTitle", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
